name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
            PROJECT_NAME: nodeApi-ec2-codedeploy
            BRANCH: main
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -r ./* $USER_NAME@$HOSTNAME:/home/ubuntu
          ssh -i private_key.pem $USER_NAME@$HOSTNAME
          cd ./$PROJECT_NAME &&
          git checkout $BRANCH &&
          git pull origin $BRANCH &&
          sudo npm i &&
          sudo npm start